language: python
python:
    - "2.7"
dist: trusty
group: deprecated-2017Q4

env:
    - CKAN_BRANCH=master
    - CKAN_BRANCH=dev-v2.8
    - CKAN_BRANCH=dev-v2.7
    - CKAN_BRANCH=dev-v2.6
    - CKAN_BRANCH=release-v2.5-latest
before_install:
    - export BOTO_CONFIG=/dev/null
install:
    - bash bin/travis-build.bash
    - pip install coveralls -U
script: sh bin/travis-run.sh
services:
    - redis-server
    - postgresql

after_success:
    - coveralls
sudo: required
